# Generated by Django 4.0.4 on 2022-09-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='MedicineTrack.status'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
