# Generated by Django 4.0.4 on 2022-08-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineTrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='MedicineTrack.status'),
        ),
    ]
