# Generated by Django 4.0.4 on 2022-09-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail',
            name='PhoneNumber_1',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
