# Generated by Django 4.0.4 on 2022-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineTrack', '0002_alter_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
