# Generated by Django 4.0.4 on 2022-08-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineTrack', '0004_remove_retail_retail_retail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='Status',
            new_name='status',
        ),
    ]
