# Generated by Django 4.0.6 on 2022-08-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineTrack', '0002_contact'),
        ('MedicineTrack', '0004_alter_order_status_alter_ordermedicine_quantity_and_more'),
    ]

    operations = [
    ]
