# Generated by Django 4.0.4 on 2022-09-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicineTrack', '0005_alter_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='photo',
        ),
        migrations.CreateModel(
            name='MedicinePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='pics/', verbose_name='Medicine photo')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicineTrack.medicine')),
            ],
        ),
    ]
